/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'loginCode' : string,
  'name' : string,
  'createdAt' : Time,
  'sector' : string,
  'address' : string,
  'contactPersonName' : string,
  'companyId' : string,
}
export interface CompanyStats {
  'activeVisitorsToday' : bigint,
  'totalVisitors' : bigint,
}
export interface Employee {
  'name' : string,
  'createdAt' : Time,
  'surname' : string,
  'employeeId' : string,
}
export type EmployeeRole = { 'owner' : null } |
  { 'authorized' : null } |
  { 'registrar' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'surname' : string,
  'employeeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifyDocumentResult {
  'name' : string,
  'surname' : string,
  'visitorId' : string,
  'companyName' : string,
  'visitPurpose' : string,
}
export interface Visitor {
  'documentCode' : string,
  'exitTime' : [] | [Time],
  'entryTime' : Time,
  'visitingPerson' : string,
  'name' : string,
  'createdBy' : string,
  'tcId' : string,
  'surname' : string,
  'visitorId' : string,
  'signatureData' : string,
  'visitPurpose' : string,
  'phone' : string,
  'companyId' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployeeToCompany' : ActorMethod<
    [string, string, EmployeeRole],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkoutVisitor' : ActorMethod<[string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyEmployees' : ActorMethod<
    [string],
    Array<{ 'role' : EmployeeRole, 'employee' : Employee }>
  >,
  'getCompanyStats' : ActorMethod<[string], CompanyStats>,
  'getMyCompanies' : ActorMethod<[string], Array<[Company, EmployeeRole]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorById' : ActorMethod<[string, string], [] | [Visitor]>,
  'getVisitors' : ActorMethod<[string], Array<Visitor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginCompany' : ActorMethod<[string], [] | [Company]>,
  'loginEmployee' : ActorMethod<[string], [] | [Employee]>,
  'registerCompany' : ActorMethod<
    [string, string, string, string],
    { 'loginCode' : string, 'companyId' : string }
  >,
  'registerEmployee' : ActorMethod<[string, string], string>,
  'registerVisitor' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'removeEmployeeFromCompany' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEmployeeRole' : ActorMethod<[string, string, EmployeeRole], undefined>,
  'updateVisitorSignature' : ActorMethod<[string, string, string], undefined>,
  'verifyDocument' : ActorMethod<[string], [] | [VerifyDocumentResult]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];