/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'action' : string,
  'logId' : string,
  'performedBy' : string,
  'timestamp' : Time,
  'details' : string,
  'targetId' : string,
  'companyId' : string,
}
export interface BlacklistEntry {
  'tcId' : string,
  'addedAt' : Time,
  'reason' : string,
}
export interface Company {
  'loginCode' : string,
  'name' : string,
  'createdAt' : Time,
  'sector' : string,
  'address' : string,
  'contactPersonName' : string,
  'companyId' : string,
}
export interface CompanyStats {
  'activeVisitorsToday' : bigint,
  'totalVisitors' : bigint,
  'totalVisitorsToday' : bigint,
}
export interface Employee {
  'name' : string,
  'createdAt' : Time,
  'surname' : string,
  'employeeId' : string,
}
export type EmployeeRole = { 'owner' : null } |
  { 'authorized' : null } |
  { 'registrar' : null };
export interface PreRegistration {
  'status' : PreRegistrationStatus,
  'visitingPerson' : string,
  'createdAt' : Time,
  'createdBy' : string,
  'tcId' : [] | [string],
  'visitorId' : [] | [string],
  'visitorName' : [] | [string],
  'inviteCode' : string,
  'visitPurpose' : string,
  'phone' : [] | [string],
  'visitorSurname' : [] | [string],
  'companyId' : string,
}
export type PreRegistrationStatus = { 'cancelled' : null } |
  { 'submitted' : null } |
  { 'pending' : null } |
  { 'finalized' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'surname' : string,
  'employeeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifyDocumentResult {
  'exitTime' : [] | [Time],
  'entryTime' : Time,
  'visitingPerson' : string,
  'name' : string,
  'surname' : string,
  'visitorId' : string,
  'companyName' : string,
  'visitPurpose' : string,
  'phone' : string,
}
export interface Visitor {
  'documentCode' : string,
  'exitTime' : [] | [Time],
  'entryTime' : Time,
  'visitingPerson' : string,
  'vehiclePlate' : [] | [string],
  'name' : string,
  'createdBy' : string,
  'tcId' : string,
  'surname' : string,
  'visitorId' : string,
  'signatureData' : string,
  'visitPurpose' : string,
  'phone' : string,
  'companyId' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployeeToCompany' : ActorMethod<
    [string, string, EmployeeRole],
    undefined
  >,
  'addEmployeeToCompanyAsCompany' : ActorMethod<
    [string, string, EmployeeRole],
    undefined
  >,
  'addVisitorBlacklist' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelInvite' : ActorMethod<[string, string], undefined>,
  'checkoutVisitor' : ActorMethod<[string, string], undefined>,
  /**
   * / PRE-REGISTRATION SYSTEM WITH PROPER AUTHORIZATION
   */
  'createInvite' : ActorMethod<[string, string, string], string>,
  'finalizeInvite' : ActorMethod<
    [string, string, string, [] | [string], [] | [string], boolean],
    string
  >,
  'getAuditLogs' : ActorMethod<[string], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyBlacklist' : ActorMethod<[string], Array<BlacklistEntry>>,
  'getCompanyEmployees' : ActorMethod<
    [string],
    Array<{ 'role' : EmployeeRole, 'employee' : Employee }>
  >,
  'getCompanyEmployeesAsCompany' : ActorMethod<
    [string],
    Array<{ 'role' : EmployeeRole, 'employee' : Employee }>
  >,
  'getCompanyInvites' : ActorMethod<[string], Array<PreRegistration>>,
  'getCompanyLogo' : ActorMethod<[string], [] | [string]>,
  'getCompanyStats' : ActorMethod<[string], CompanyStats>,
  'getCompanyStatsAsCompany' : ActorMethod<[string], [] | [CompanyStats]>,
  'getInvitePublic' : ActorMethod<
    [string],
    [] | [
      {
        'status' : PreRegistrationStatus,
        'visitingPerson' : string,
        'companyName' : string,
        'visitPurpose' : string,
      }
    ]
  >,
  'getMyCompanies' : ActorMethod<[string], Array<[Company, EmployeeRole]>>,
  'getPurposeDistributionAsCompany' : ActorMethod<
    [string],
    Array<[string, bigint]>
  >,
  'getTopVisitedPersons' : ActorMethod<
    [string, bigint],
    Array<[string, bigint]>
  >,
  'getTopVisitedPersonsAsCompany' : ActorMethod<
    [string, bigint],
    Array<[string, bigint]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorById' : ActorMethod<[string, string], [] | [Visitor]>,
  'getVisitorCountByTcId' : ActorMethod<[string, string], bigint>,
  'getVisitors' : ActorMethod<[string], Array<Visitor>>,
  'getVisitorsAsCompany' : ActorMethod<[string], Array<Visitor>>,
  'getVisitorsByPerson' : ActorMethod<[string, string], Array<Visitor>>,
  'getVisitorsByTcId' : ActorMethod<[string, string], Array<Visitor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isVisitorBlacklisted' : ActorMethod<[string, string], boolean>,
  'loginCompany' : ActorMethod<[string], [] | [Company]>,
  'loginEmployee' : ActorMethod<[string], [] | [Employee]>,
  'registerCompany' : ActorMethod<
    [string, string, string, string],
    { 'loginCode' : string, 'companyId' : string }
  >,
  'registerEmployee' : ActorMethod<[string, string], string>,
  'registerVisitor' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    string
  >,
  'removeEmployeeFromCompany' : ActorMethod<[string, string], undefined>,
  'removeEmployeeFromCompanyAsCompany' : ActorMethod<[string, string], undefined>,
  'removeVisitorBlacklist' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCompanyLogo' : ActorMethod<[string, string], undefined>,
  'setEmployeePin' : ActorMethod<[string, string], undefined>,
  'setEmployeeRole' : ActorMethod<[string, string, EmployeeRole], undefined>,
  'setEmployeeRoleAsCompany' : ActorMethod<[string, string, EmployeeRole], undefined>,
  'submitInviteInfo' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateCompanyProfile' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateVisitorSignature' : ActorMethod<[string, string, string], undefined>,
  'verifyDocument' : ActorMethod<[string], [] | [VerifyDocumentResult]>,
  'verifyEmployeePin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];