/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmployeeRole = IDL.Variant({
  'owner' : IDL.Null,
  'authorized' : IDL.Null,
  'registrar' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'surname' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const Employee = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'surname' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const CompanyStats = IDL.Record({
  'activeVisitorsToday' : IDL.Nat,
  'totalVisitors' : IDL.Nat,
  'totalVisitorsToday' : IDL.Nat,
});
export const Company = IDL.Record({
  'loginCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'sector' : IDL.Text,
  'address' : IDL.Text,
  'contactPersonName' : IDL.Text,
  'companyId' : IDL.Text,
});
export const Visitor = IDL.Record({
  'documentCode' : IDL.Text,
  'exitTime' : IDL.Opt(Time),
  'entryTime' : Time,
  'visitingPerson' : IDL.Text,
  'vehiclePlate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdBy' : IDL.Text,
  'tcId' : IDL.Text,
  'surname' : IDL.Text,
  'visitorId' : IDL.Text,
  'signatureData' : IDL.Text,
  'visitPurpose' : IDL.Text,
  'phone' : IDL.Text,
  'companyId' : IDL.Text,
});
export const VerifyDocumentResult = IDL.Record({
  'exitTime' : IDL.Opt(Time),
  'entryTime' : Time,
  'visitingPerson' : IDL.Text,
  'name' : IDL.Text,
  'surname' : IDL.Text,
  'visitorId' : IDL.Text,
  'companyName' : IDL.Text,
  'visitPurpose' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployeeToCompany' : IDL.Func([IDL.Text, IDL.Text, EmployeeRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkoutVisitor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyEmployees' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Record({ 'role' : EmployeeRole, 'employee' : Employee }))],
      ['query'],
    ),
  'getCompanyLogo' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCompanyStats' : IDL.Func([IDL.Text], [CompanyStats], ['query']),
  'getCompanyStatsAsCompany' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CompanyStats)],
      ['query'],
    ),
  'getMyCompanies' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Company, EmployeeRole))],
      ['query'],
    ),
  'getPurposeDistributionAsCompany' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTopVisitedPersons' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTopVisitedPersonsAsCompany' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorById' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Visitor)],
      ['query'],
    ),
  'getVisitorCountByTcId' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'getVisitors' : IDL.Func([IDL.Text], [IDL.Vec(Visitor)], ['query']),
  'getVisitorsAsCompany' : IDL.Func([IDL.Text], [IDL.Vec(Visitor)], ['query']),
  'getVisitorsByPerson' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Visitor)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'loginEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'registerCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'loginCode' : IDL.Text, 'companyId' : IDL.Text })],
      [],
    ),
  'registerEmployee' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'registerVisitor' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'removeEmployeeFromCompany' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCompanyLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setEmployeePin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setEmployeeRole' : IDL.Func([IDL.Text, IDL.Text, EmployeeRole], [], []),
  'updateCompanyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateVisitorSignature' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyDocument' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VerifyDocumentResult)],
      ['query'],
    ),
  'verifyEmployeePin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmployeeRole = IDL.Variant({
    'owner' : IDL.Null,
    'authorized' : IDL.Null,
    'registrar' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'surname' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const Employee = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'surname' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const CompanyStats = IDL.Record({
    'activeVisitorsToday' : IDL.Nat,
    'totalVisitors' : IDL.Nat,
    'totalVisitorsToday' : IDL.Nat,
  });
  const Company = IDL.Record({
    'loginCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'sector' : IDL.Text,
    'address' : IDL.Text,
    'contactPersonName' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const Visitor = IDL.Record({
    'documentCode' : IDL.Text,
    'exitTime' : IDL.Opt(Time),
    'entryTime' : Time,
    'visitingPerson' : IDL.Text,
    'vehiclePlate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdBy' : IDL.Text,
    'tcId' : IDL.Text,
    'surname' : IDL.Text,
    'visitorId' : IDL.Text,
    'signatureData' : IDL.Text,
    'visitPurpose' : IDL.Text,
    'phone' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const VerifyDocumentResult = IDL.Record({
    'exitTime' : IDL.Opt(Time),
    'entryTime' : Time,
    'visitingPerson' : IDL.Text,
    'name' : IDL.Text,
    'surname' : IDL.Text,
    'visitorId' : IDL.Text,
    'companyName' : IDL.Text,
    'visitPurpose' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployeeToCompany' : IDL.Func(
        [IDL.Text, IDL.Text, EmployeeRole],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkoutVisitor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyEmployees' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Record({ 'role' : EmployeeRole, 'employee' : Employee }))],
        ['query'],
      ),
    'getCompanyLogo' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCompanyStats' : IDL.Func([IDL.Text], [CompanyStats], ['query']),
    'getCompanyStatsAsCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CompanyStats)],
        ['query'],
      ),
    'getMyCompanies' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Company, EmployeeRole))],
        ['query'],
      ),
    'getPurposeDistributionAsCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTopVisitedPersons' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTopVisitedPersonsAsCompany' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorById' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Visitor)],
        ['query'],
      ),
    'getVisitorCountByTcId' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getVisitors' : IDL.Func([IDL.Text], [IDL.Vec(Visitor)], ['query']),
    'getVisitorsAsCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Visitor)],
        ['query'],
      ),
    'getVisitorsByPerson' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Visitor)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'loginEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'registerCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'loginCode' : IDL.Text, 'companyId' : IDL.Text })],
        [],
      ),
    'registerEmployee' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'registerVisitor' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'removeEmployeeFromCompany' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCompanyLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setEmployeePin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setEmployeeRole' : IDL.Func([IDL.Text, IDL.Text, EmployeeRole], [], []),
    'updateCompanyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateVisitorSignature' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyDocument' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VerifyDocumentResult)],
        ['query'],
      ),
    'verifyEmployeePin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };