/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Company {
    loginCode: string;
    name: string;
    createdAt: Time;
    sector: string;
    address: string;
    contactPersonName: string;
    companyId: string;
}
export type Time = bigint;
export interface VerifyDocumentResult {
    name: string;
    surname: string;
    visitorId: string;
    companyName: string;
    visitPurpose: string;
}
export interface Employee {
    name: string;
    createdAt: Time;
    surname: string;
    employeeId: string;
}
export interface Visitor {
    documentCode: string;
    exitTime?: Time;
    entryTime: Time;
    visitingPerson: string;
    name: string;
    createdBy: string;
    tcId: string;
    surname: string;
    visitorId: string;
    signatureData: string;
    visitPurpose: string;
    phone: string;
    companyId: string;
}
export interface UserProfile {
    name: string;
    surname: string;
    employeeId?: string;
}
export interface CompanyStats {
    activeVisitorsToday: bigint;
    totalVisitors: bigint;
}
export enum EmployeeRole {
    owner = "owner",
    authorized = "authorized",
    registrar = "registrar"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEmployeeToCompany(companyId: string, employeeId: string, role: EmployeeRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkoutVisitor(visitorId: string, companyId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyEmployees(companyId: string): Promise<Array<{
        role: EmployeeRole;
        employee: Employee;
    }>>;
    getCompanyStats(companyId: string): Promise<CompanyStats>;
    getMyCompanies(employeeId: string): Promise<Array<[Company, EmployeeRole]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitorById(visitorId: string, companyId: string): Promise<Visitor | null>;
    getVisitors(companyId: string): Promise<Array<Visitor>>;
    isCallerAdmin(): Promise<boolean>;
    loginCompany(loginCode: string): Promise<Company | null>;
    loginEmployee(employeeId: string): Promise<Employee | null>;
    registerCompany(name: string, sector: string, address: string, contactPersonName: string): Promise<{
        loginCode: string;
        companyId: string;
    }>;
    registerEmployee(name: string, surname: string): Promise<string>;
    registerVisitor(companyId: string, name: string, surname: string, tcId: string, phone: string, visitingPerson: string, visitPurpose: string, signatureData: string): Promise<string>;
    removeEmployeeFromCompany(companyId: string, targetEmployeeId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setEmployeeRole(companyId: string, targetEmployeeId: string, role: EmployeeRole): Promise<void>;
    updateVisitorSignature(visitorId: string, companyId: string, signatureData: string): Promise<void>;
    verifyDocument(documentCode: string): Promise<VerifyDocumentResult | null>;
}
import type { Company as _Company, Employee as _Employee, EmployeeRole as _EmployeeRole, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VerifyDocumentResult as _VerifyDocumentResult, Visitor as _Visitor } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEmployeeToCompany(arg0: string, arg1: string, arg2: EmployeeRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployeeToCompany(arg0, arg1, to_candid_EmployeeRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployeeToCompany(arg0, arg1, to_candid_EmployeeRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkoutVisitor(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutVisitor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutVisitor(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyEmployees(arg0: string): Promise<Array<{
        role: EmployeeRole;
        employee: Employee;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyEmployees(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyEmployees(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyStats(arg0: string): Promise<CompanyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyStats(arg0);
            return result;
        }
    }
    async getMyCompanies(arg0: string): Promise<Array<[Company, EmployeeRole]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCompanies(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCompanies(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitorById(arg0: string, arg1: string): Promise<Visitor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorById(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorById(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitors(arg0: string): Promise<Array<Visitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitors(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitors(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginCompany(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCompany(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCompany(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginEmployee(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginEmployee(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCompany(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        loginCode: string;
        companyId: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCompany(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCompany(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async registerEmployee(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEmployee(arg0, arg1);
            return result;
        }
    }
    async registerVisitor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVisitor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVisitor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async removeEmployeeFromCompany(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEmployeeFromCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEmployeeFromCompany(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setEmployeeRole(arg0: string, arg1: string, arg2: EmployeeRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmployeeRole(arg0, arg1, to_candid_EmployeeRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmployeeRole(arg0, arg1, to_candid_EmployeeRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateVisitorSignature(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisitorSignature(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisitorSignature(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyDocument(arg0: string): Promise<VerifyDocumentResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDocument(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDocument(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EmployeeRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Visitor_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visitor): Visitor {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Visitor]): Visitor | null {
    return value.length === 0 ? null : from_candid_Visitor_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Company]): Company | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VerifyDocumentResult]): VerifyDocumentResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _EmployeeRole;
    employee: _Employee;
}): {
    role: EmployeeRole;
    employee: Employee;
} {
    return {
        role: from_candid_EmployeeRole_n13(_uploadFile, _downloadFile, value.role),
        employee: value.employee
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documentCode: string;
    exitTime: [] | [_Time];
    entryTime: _Time;
    visitingPerson: string;
    name: string;
    createdBy: string;
    tcId: string;
    surname: string;
    visitorId: string;
    signatureData: string;
    visitPurpose: string;
    phone: string;
    companyId: string;
}): {
    documentCode: string;
    exitTime?: Time;
    entryTime: Time;
    visitingPerson: string;
    name: string;
    createdBy: string;
    tcId: string;
    surname: string;
    visitorId: string;
    signatureData: string;
    visitPurpose: string;
    phone: string;
    companyId: string;
} {
    return {
        documentCode: value.documentCode,
        exitTime: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.exitTime)),
        entryTime: value.entryTime,
        visitingPerson: value.visitingPerson,
        name: value.name,
        createdBy: value.createdBy,
        tcId: value.tcId,
        surname: value.surname,
        visitorId: value.visitorId,
        signatureData: value.signatureData,
        visitPurpose: value.visitPurpose,
        phone: value.phone,
        companyId: value.companyId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    surname: string;
    employeeId: [] | [string];
}): {
    name: string;
    surname: string;
    employeeId?: string;
} {
    return {
        name: value.name,
        surname: value.surname,
        employeeId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_tuple_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Company, _EmployeeRole]): [Company, EmployeeRole] {
    return [
        value[0],
        from_candid_EmployeeRole_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: null;
} | {
    authorized: null;
} | {
    registrar: null;
}): EmployeeRole {
    return "owner" in value ? EmployeeRole.owner : "authorized" in value ? EmployeeRole.authorized : "registrar" in value ? EmployeeRole.registrar : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    role: _EmployeeRole;
    employee: _Employee;
}>): Array<{
    role: EmployeeRole;
    employee: Employee;
}> {
    return value.map((x)=>from_candid_record_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Company, _EmployeeRole]>): Array<[Company, EmployeeRole]> {
    return value.map((x)=>from_candid_tuple_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Visitor>): Array<Visitor> {
    return value.map((x)=>from_candid_Visitor_n18(_uploadFile, _downloadFile, x));
}
function to_candid_EmployeeRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    surname: string;
    employeeId?: string;
}): {
    name: string;
    surname: string;
    employeeId: [] | [string];
} {
    return {
        name: value.name,
        surname: value.surname,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    owner: null;
} | {
    authorized: null;
} | {
    registrar: null;
} {
    return value == EmployeeRole.owner ? {
        owner: null
    } : value == EmployeeRole.authorized ? {
        authorized: null
    } : value == EmployeeRole.registrar ? {
        registrar: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
